### ISSUE TITLE
What does "Depending on your computer, the belt may not reach this speed" mean?

### ISSUE THREAD

**Issue by mateusscheper** [budak7273/BeltMk6#1]
Hey! 

What does "Depending on your computer, the belt may not reach this speed" mean exactly? GPU memory? CPU? RAM? 
I'm getting like 650~ items per minute, but I'm not sure what's causing it, since I don't see any hardware hitting 100%. 

Thanks!

**Comment by budak7273** [comment]
It's entirely controlled by the base game's logic; I don't know what that is and there is nothing I can do to change it.

Can you send a screenshot of the setup you used to test the speed?

How many items do you get with a base-game belt mk5? That's supposed to move 780/min.

**Comment by budak7273** [comment]
Please reopen this issue once you have the info I requested
